"""add_war_statistics_table

Revision ID: 64d3eba70572
Revises: 0002_enable_user_schedule
Create Date: 2026-04-12 22:09:16.405471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d3eba70572'
down_revision = '0002_enable_user_schedule'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('war_statistics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('personnel_units', sa.Integer(), nullable=True),
    sa.Column('personnel_units_inc', sa.Integer(), nullable=True),
    sa.Column('tanks', sa.Integer(), nullable=True),
    sa.Column('tanks_inc', sa.Integer(), nullable=True),
    sa.Column('armoured_fighting_vehicles', sa.Integer(), nullable=True),
    sa.Column('armoured_fighting_vehicles_inc', sa.Integer(), nullable=True),
    sa.Column('artillery_systems', sa.Integer(), nullable=True),
    sa.Column('artillery_systems_inc', sa.Integer(), nullable=True),
    sa.Column('mlrs', sa.Integer(), nullable=True),
    sa.Column('mlrs_inc', sa.Integer(), nullable=True),
    sa.Column('aa_warfare_systems', sa.Integer(), nullable=True),
    sa.Column('aa_warfare_systems_inc', sa.Integer(), nullable=True),
    sa.Column('planes', sa.Integer(), nullable=True),
    sa.Column('planes_inc', sa.Integer(), nullable=True),
    sa.Column('helicopters', sa.Integer(), nullable=True),
    sa.Column('helicopters_inc', sa.Integer(), nullable=True),
    sa.Column('vehicles_fuel_tanks', sa.Integer(), nullable=True),
    sa.Column('vehicles_fuel_tanks_inc', sa.Integer(), nullable=True),
    sa.Column('warships_cutters', sa.Integer(), nullable=True),
    sa.Column('warships_cutters_inc', sa.Integer(), nullable=True),
    sa.Column('cruise_missiles', sa.Integer(), nullable=True),
    sa.Column('cruise_missiles_inc', sa.Integer(), nullable=True),
    sa.Column('uav_systems', sa.Integer(), nullable=True),
    sa.Column('uav_systems_inc', sa.Integer(), nullable=True),
    sa.Column('special_military_equip', sa.Integer(), nullable=True),
    sa.Column('special_military_equip_inc', sa.Integer(), nullable=True),
    sa.Column('atgm_srbm_systems', sa.Integer(), nullable=True),
    sa.Column('atgm_srbm_systems_inc', sa.Integer(), nullable=True),
    sa.Column('submarines', sa.Integer(), nullable=True),
    sa.Column('submarines_inc', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('war_statistics')
    # ### end Alembic commands ###
